export const SITES = [
  {
    id: 'za',
    name: 'revibe.co.za',
    baseUrl: 'https://revibe.co.za',
    plpPath: '/collections/all',
    region: 'South Africa',
    language: 'en',
    rtl: false,
    currency: { code: 'ZAR', symbols: ['R', 'ZAR'] },
    bnpl: ['FLOAT', 'PAYFLEX', 'HAPPYPAY'],
    warrantyTiers: [
      { maxPrice: 2892,  warranty: 450 },
      { maxPrice: 4821,  warranty: 795 },
      { maxPrice: 9642,  warranty: 1420 },
      { maxPrice: 14463, warranty: 2350 },
      { maxPrice: Infinity, warranty: 2600 },
    ],
  },
  {
    id: 'ae',
    name: 'revibe.me',
    baseUrl: 'https://revibe.me',
    plpPath: '/collections/all',
    region: 'United Arab Emirates',
    language: 'en',
    rtl: false,
    currency: { code: 'AED', symbols: ['AED', 'د.إ'] },
    bnpl: ['Tabby', 'Tamara'],
    warrantyTiers: [
      { maxPrice: 600,  warranty: 75 },
      { maxPrice: 1000, warranty: 125 },
      { maxPrice: 2000, warranty: 215 },
      { maxPrice: 3000, warranty: 395 },
      { maxPrice: Infinity, warranty: 445 },
    ],
  },
  {
    id: 'sa',
    name: 'sa.revibe.me',
    baseUrl: 'https://sa.revibe.me',
    plpPath: '/collections/all',
    region: 'Saudi Arabia',
    language: 'en',
    rtl: false,
    currency: { code: 'SAR', symbols: ['SAR', 'ر.س'] },
    bnpl: ['Tabby', 'Tamara', 'Baseeta'],
    warrantyTiers: [
      { maxPrice: 600,  warranty: 75 },
      { maxPrice: 1000, warranty: 125 },
      { maxPrice: 2000, warranty: 215 },
      { maxPrice: 3000, warranty: 395 },
      { maxPrice: Infinity, warranty: 445 },
    ],
  },
];
